### ISSUE TITLE
openpyxl package possibly missing from requirements?

### ISSUE THREAD

**Issue by helenahahne** [tum-ewk/OpenTUMFlex#75]
When I wanted to save the flex offers as .xlsx-Files, I had to install/add 'openpyxl' to the OpenTUMFlex environment for it to work, so maybe this should be added to the requirements? 

Concerns: generate_market_offers.py  --- "to_excel"  (line 56)

**Comment by ThinkingKNB** [comment]
Thanks for pointing it out @helenahahne.
